# Site settings
title: MixChamp
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mix.champ.gg" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
