# Site settings
title: PugChamp
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pug.champ.gg" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
